servo_v4: Don't initialize servo_v4_role.
In order to use the control as a remote power switch we should NOT
initialize it as part of hwinit in order to avoid autotest changing
the setting back unexpectedly here:

https://chromium.googlesource.com/chromiumos/third_party/autotest/+/master/server/cros/servo/servo.py#276

Change also removes some unneeded clobber_ok keyvals.

BUG=b:37219390
TEST=manual,
  IP=1.1.1.1
  CTEST=power_LoadTest.1hour
  sudo servod
  dut-control dut-control servo_v4_role:snk
  test_that --fast $IP power_ServodWrapper \
     --autotest_dir ~/trunk/src/third_party/autotest/files \
     --args "test=${CTEST} servo_host=localhost servo_port=9999 ina_rate=1 vbat_rate=2"

See test complete successfully instead of printing
  ERROR: Running on AC power. Please remove AC power cable.

Change-Id: I450744afb6782c8f50cdd39e58b48929c3cfc2ae
Reviewed-on: https://chromium-review.googlesource.com/1355465
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Todd Broch <tbroch@chromium.org>
Reviewed-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>