xmlrpc: fix faulty Fault import
During a recent refactor, xmlrpclib is not available but rather the
Server itself. This means that we need to import Fault as well to catch
the errors.

BUG=b:156987864
TEST=sudo servod -b soraka & // tot
dut-control ec_board3
NameError: global name 'xmlrpclib' is not defined

TEST=sudo servod -b soraka & // with fix
dut-control ec_board3
Problem with ['ec_board3'] :: No control named "ec_board3"

TEST=grep -r 'xmlrpclib'
//inspect remaining notions are comments or imports

Change-Id: Ic3cd99fe56940cbc934fc205dcd5f61d980405f8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/2209420
Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Reviewed-by: Puthikorn Voravootivat <puthik@chromium.org>
Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>