hdctools: fixup active_v4_device reference path.
BUG=b:137763487
TEST=start servod w/ just single servo V4

and no longer see,
  NameError: global name 'activeV4DeviceError' is not defined

Change-Id: I93971d5d0ff4bb7026af64f0a76de8cd76f9fbb1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/1935507
Tested-by: Todd Broch <tbroch@chromium.org>
Reviewed-by: Namyoon Woo <namyoon@chromium.org>
Reviewed-by: Mary Ruthven <mruthven@chromium.org>
Auto-Submit: Todd Broch <tbroch@chromium.org>
Commit-Queue: Todd Broch <tbroch@chromium.org>