servod: Include NameError as a "known" exception.
The logging for a missing control is overly attention-grabbing
("please take a look").  This demotes the message to something
more routine.

Before:
ERROR: (NameError) Unknown issue setting active_v4_device -> default. Please take a look in the DEBUG logs.

After:
ERROR: (NameError) Failed setting active_v4_device -> default: No control named active_v4_device. All controls:

BUG=chromium:1079045
TEST=Run servod with the change, try setting active_v4_device.

Change-Id: I32f45ddde828e6444f21fe2a3900ded38b8771ca
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/2189881
Tested-by: Dana Goyette <dgoyette@chromium.org>
Reviewed-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>