servo_logging: Get the handled exception types from the caller.
The logging change introduced a new import, which breaks the
dut-console script:

  ~/chromiumos/src/platform/dev/contrib$ ./dut-console -c cpu
  Traceback (most recent call last):
    File "chromiumos/src/platform/dev/contrib/../../../../chroot/usr/lib64/python2.7/site-packages/servo/dut_control.py", line 21, in <module>
      import servo_parsing
    File "chromiumos/chroot/usr/lib64/python2.7/site-packages/servo/servo_parsing.py", line 12, in <module>
      import servo_logging
    File "chromiumos/chroot/usr/lib64/python2.7/site-packages/servo/servo_logging.py", line 37, in <module>
      from .drv import hw_driver
  ValueError: Attempted relative import in non-package
  Cannot find pty cpu_uart_pty.

By moving the choice of exception class into the caller, this extra
import can be avoided.

BUG=None
TEST=Run servod, check for logging of commands.
TEST=Run dut-console, from contrib.

Change-Id: I9b5eb4c8f6bebf3ec6dcc30bdd5a532eb100ec1a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/2095383
Tested-by: Dana Goyette <dgoyette@chromium.org>
Tested-by: Stephen Boyd <swboyd@chromium.org>
Reviewed-by: Stephen Boyd <swboyd@chromium.org>
Reviewed-by: Denis Brockus <dbrockus@chromium.org>
Reviewed-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Commit-Queue: Dana Goyette <dgoyette@chromium.org>