servod: remove gale_power from __init__.py
BUG=chromium:665097
TEST=sudo servod -b reef launches w/o error
ImportError: No module named gale_power

Change-Id: I1785dd891805e5b4a0e2ace6c40d0901b109e316
Reviewed-on: https://chromium-review.googlesource.com/395668
Commit-Ready: Todd Broch <tbroch@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-by: John Carey <ranix@google.com>
Reviewed-by: Julio Diez <jdiez@chromium.org>
(cherry picked from commit 4fa50147be699ab3c4f751e336939633fefff042)
Reviewed-on: https://chromium-review.googlesource.com/411320
Commit-Queue: Todd Broch <tbroch@chromium.org>
Reviewed-by: danny chan <dchan@chromium.org>