servod: In Fi2c.__del__(), do not assume a parent class has __del__().
This resolves an exception that gets printed and suppressed when the
FTDI I2C object gets deleted unexpectedly when servod crashes on startup
(due to an unrelated bug).

Sample error that this change resolves:

Exception AttributeError: "'super' object has no attribute '__del__'" in <bound method Fi2c.__del__ of <servo.ftdii2c.Fi2c object at 0x7f6af97bab50>> ignored

BUG=none
TEST=Ran servod --board=atlas with servo_v2 before and after this change.
This change removes the error shown above.

Change-Id: I59eda4447e0f490b47a8c7fdee83bf99d82e1906
Signed-off-by: Matthew Blecker <matthewb@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1583144
Reviewed-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>